# Generated by Django 4.2 on 2023-09-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailcampaigns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCampaign',
        ),
    ]
